apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: $MYAPP
  name: $MYAPP
spec:
  replicas: 1
  selector:
    matchLabels:
      run: $MYAPP
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: $MYAPP
    spec:
      containers:
      - image: $MYREPO/$MYAPP
        name: $MYAPP
        ports:
        - containerPort: 5000
        resources: {}
